{
 "title": "Dashboard Weather API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Latencia Media para Endpoints Rápidos",
   "type": "timeseries",
   "description": "Tiempo promedio de respuesta en segundos por endpoint excluyendo IA. Se usa un intervalo de 5 minutos para evitar suavizar cambios en tendencia general.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_durations_seconds_sum{route!~\"/api/v1/ai.*\"}[5m]) / rate(http_request_durations_seconds_count{route!~\"/api/v1/ai.*\"}[5m])",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Latencia Media Endpoint IA",
   "type": "timeseries",
   "description": "Se reserva un panel para el tiempo de respuesta del endpoint de IA porque su tiempo de respuesta es mucho mayor que el resto de endpoints.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_durations_seconds_sum{route=~\"/api/v1/ai.*\"}[5m]) / rate(http_request_durations_seconds_count{route=~\"/api/v1/ai.*\"}[5m])",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Requests por Segundo",
   "type": "timeseries",
   "description": "Número de peticiones por segundo para cada endpoint calculada en intervalos de un minuto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_durations_seconds_count[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% de peticiones deben tardar menos de....",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_durations_seconds_bucket[5m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Total de Peticiones",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_durations_seconds_count) by (route)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}